service: shop-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ap-northeast-1"}
  environment:
    STAGE: ${self:provider.stage}

custom:
  environment:
    dev:
      APP_ENV: dev
    stg:
      APP_ENV: stg
    prd:
      APP_ENV: prd

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    name: ${self:service}-${self:provider.stage}--hello
    environment: ${self:custom.environment.${self:provider.stage}}
    events:
      - httpApi:
          path: /hello
          method: get

  world:
    handler: bin/world
    name: ${self:service}-${self:provider.stage}--world
    environment: ${self:custom.environment.${self:provider.stage}}
    events:
      - httpApi:
          path: /world
          method: get
