service: shop-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ap-northeast-1"}
  environment:
    STAGE: ${self:provider.stage}
    APP_ENV: ${self:provider.stage}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    name: ${self:service}-${self:provider.stage}--hello
    events:
      - httpApi:
          path: /hello
          method: get

  world:
    handler: bin/world
    name: ${self:service}-${self:provider.stage}--world
    events:
      - httpApi:
          path: /world
          method: get
