service: shop-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ap-northeast-1"}
  environment: ${file(.env.yml)}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions: ${file(functions.yml)}
