name: Production CI for Shop API

on:
  push:
    branches:
      - main
    paths:
      - 'shop-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      STAGE: prd

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install deployment tools
        run: |
          npm i -g serverless

      - name: Setting env
        run: |
          echo -n > .env.yml
          echo "APP_ENV: ${{ env.STAGE }}"       >> .env.yml
          echo "APP_REVISION: ${{ github.sha }}" >> .env.yml
        working-directory: ./shop-api

      - name: Build
        run: |
          make build
        working-directory: ./shop-api

      - name: Deploy
        run: |
          sls deploy --stage ${{ env.STAGE }}
        working-directory: ./shop-api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Notify result to slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Production CI for Shop API*'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
